// <auto-generated />
namespace PetCare_system.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MigAvailableRemovve : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MigAvailableRemovve));
        
        string IMigrationMetadata.Id
        {
            get { return "202504151133392_MigAvailableRemovve"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
