// <auto-generated />
namespace PetCare_system.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migrMembership : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrMembership));
        
        string IMigrationMetadata.Id
        {
            get { return "202504032116580_migrMembership"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
